//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS.Websites;

namespace X
{
	/// <summary>
	/// Represents a page of type <see cref="Navitem"/>.
	/// </summary>
	public partial class Navitem : IWebPageFieldsSource
	{
		/// <summary>
		/// Code name of the content type.
		/// </summary>
		public const string CONTENT_TYPE_NAME = "x.navitem";


		/// <summary>
		/// Represents system properties for a web page item.
		/// </summary>
		public WebPageFields SystemFields { get; set; }


		/// <summary>
		/// Name.
		/// </summary>
		public string Name { get; set; }


		/// <summary>
		/// Url.
		/// </summary>
		public string Url { get; set; }


		/// <summary>
		/// UrlType.
		/// </summary>
		public string UrlType { get; set; }
	}
}