//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS.Websites;
using CMS.MediaLibrary;

namespace X
{
	/// <summary>
	/// Represents a page of type <see cref="Article"/>.
	/// </summary>
	public partial class Article : IWebPageFieldsSource
	{
		/// <summary>
		/// Code name of the content type.
		/// </summary>
		public const string CONTENT_TYPE_NAME = "x.article";


		/// <summary>
		/// Represents system properties for a web page item.
		/// </summary>
		public WebPageFields SystemFields { get; set; }


		/// <summary>
		/// ArticleTitle.
		/// </summary>
		public string ArticleTitle { get; set; }


		/// <summary>
		/// ArticleDescription.
		/// </summary>
		public string ArticleDescription { get; set; }


		/// <summary>
		/// ArticleTeaser.
		/// </summary>
		public IEnumerable<AssetRelatedItem> ArticleTeaser { get; set; }


		/// <summary>
		/// ArticleBanner.
		/// </summary>
		public IEnumerable<AssetRelatedItem> ArticleBanner { get; set; }
	}
}