//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS.ContentEngine;

namespace X
{
	/// <summary>
	/// Represents a content item of type <see cref="Faq"/>.
	/// </summary>
	public partial class Faq
	{
		/// <summary>
		/// Code name of the content type.
		/// </summary>
		public const string CONTENT_TYPE_NAME = "x.faq";


		/// <summary>
		/// Represents system properties for a content item.
		/// </summary>
		public ContentItemFields SystemFields { get; set; }


		/// <summary>
		/// FaqQuestion.
		/// </summary>
		public string FaqQuestion { get; set; }


		/// <summary>
		/// FaqAnswer.
		/// </summary>
		public string FaqAnswer { get; set; }
	}
}